from pydantic import BaseModel, Field
from typing import List, Dict, Any

class QueryRequest(BaseModel):
    """Schema for incoming Q&A queries."""
    question: str = Field(..., examples=["What pricing plan includes API access?"])

class QueryResponse(BaseModel):
    """Schema for outgoing Q&A responses."""
    answer: str = Field(..., description="Context-constrained answer generated by the LLM.")
    sources: List[str] = Field(..., description="Attributed list of source filenames.")
    latency_ms: int = Field(..., description="Query processing latency in milliseconds.")

class HealthResponse(BaseModel):
    """Schema for server health reports."""
    status: str = Field(..., examples=["healthy"])
    details: Dict[str, Any] = Field(default_factory=dict)
